# render.yaml
services:
  # Service API (Web Service)
  - type: web
    name: pam test-drive # Ou le nom que vous voulez/avez dans Render
    env: docker
    repo: https://github.com/ydjemai93/test-drive.git # <-- METTEZ L'URL DE VOTRE REPO
    branch: main # Ou votre branche de déploiement
    dockerfilePath: ./Dockerfile.api # Chemin vers le Dockerfile API
    startCommand: uvicorn api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - fromGroup: env-demo # Nom de votre groupe d'environnement partagé

  # Service Agent (Background Worker)
  - type: worker # Type Worker pour l'agent persistant
    name: test-drive # Ou le nom que vous voulez/avez dans Render
    env: docker
    repo: https://github.com/ydjemai93/test-drive.git # <-- METTEZ L'URL DE VOTRE REPO
    branch: main # Ou votre branche de déploiement
    dockerfilePath: ./Dockerfile.agent # Chemin vers le Dockerfile Agent
    # S'exécute dans le WORKDIR défini dans Dockerfile.agent (/app/outbound)
    startCommand: python agent.py
    envVars:
      - fromGroup: env-demo # Nom de votre groupe d'environnement partagé

# Optionnel: Définir le groupe d'environnement ici si vous ne l'avez pas fait dans l'UI
# envVarGroups:
#   - name: pam-demo-shared-env
#     envVars:
#       - key: LIVEKIT_URL
#         value: VOTRE_URL
#       - key: LIVEKIT_API_KEY
#         sync: false # Recommandé pour les secrets
#       - key: LIVEKIT_API_SECRET
#         sync: false # Recommandé pour les secrets
#       # ... Ajoutez TOUTES les autres variables ici ...
